# Generated by Django 2.2.12 on 2020-06-03 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.Chat')),
            ],
        ),
    ]
