# Generated by Django 2.2.12 on 2020-06-03 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='telegram.Chat'),
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('chat', 'code')},
        ),
    ]
