# Generated by Django 2.2.12 on 2020-06-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_auto_20200603_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
