# Generated by Django 2.2.12 on 2020-06-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_node_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='status',
            field=models.CharField(choices=[('', ''), ('r', 'result'), ('s', 'start')], default='', max_length=1),
        ),
    ]
