# Generated by Django 2.2.12 on 2020-06-01 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_node_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='node_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='node',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Probability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('child_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='api.State')),
                ('parent_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='api.State')),
            ],
        ),
    ]
