# Generated by Django 2.2.12 on 2020-06-01 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200601_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='api.Node'),
        ),
    ]
